name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Nightly Build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    steps:
      # - name: Github checkout
      #   uses: actions/checkout@v4
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Update package.json version
      #   run: npm --no-git-tag-version --preid=$(date +%Y%m%d) version prerelease

      # - name: Install dependencies
      #   run: npm ci

      # - name: Build app
      #   run: npm run build

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: MongoDB Query Executor
      #     path: ./release/**/*.dmg

      - name: Trigger Acceptance Stage
        run: |
          gh workflow run AcceptanceStage.yml \
          --repo vaisakhsasikumar/electron-app-tests \
          --field event_type=fresh-artifact \
          --field run_id=${{ github.run_id }}
