# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

permissions: write-all

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@vaisakhsasikumar'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Pack app
        run: npm pack

      - name: Get package name and version
        id: get_package_info
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name.split('/')[1]")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_TAR=${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz" >> $GITHUB_ENV

      - name: Publish specific tarball
        run: |
          echo "Publishing: $PACKAGE_TAR"
          npm publish ./$PACKAGE_TAR --access public --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}