# This workflow will build an electron application using npm and then publish it to GitHub Packages when a release is created.
# It updates the version in package.json for each release with a pre-release identifier based on the current date,
# and uploads the built artifacts (in this case, .dmg files) as an upload artifact.
# For more information, see: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md


name: Publish .dmg installer to Release

on:
  release:
    types: [created]


permissions: write-all

jobs:
  build:
    name: Nightly Build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macos-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update package.json version
        run: npm version prerelease

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MongoDB Query Executor
          path: ./release/**/*.dmg
