name: Reusable workflow example

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      run_id:
        required: true
        type: string

jobs:
  triage:
    runs-on: macos-latest
    steps:
      - name: test
        run: echo ${{ inputs.tag_name }} ${{ inputs.run_id }}
