name: Commit Stage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  commit:
    name: Commit Stage
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Compile Code
        run: npx tsc

      - name: Run Unit Tests
        run: npm run test

      - name: Run Narrow Integration Tests
        # TODO: replace with command for Narrow Integration Tests
        run: npm run test

      - name: Run Component Tests
        # TODO: replace with command for Component Tests
        run: npm run test

      - name: Run Component Tests
        # TODO: replace with command for Contract Provider Verification Tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build
