name: Commit Stage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  compile:
    name: Compile Code
    runs-on: macos-latest
    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Compile Code
        run: npx tsc

  unit_tests:
    name: Run Unit Tests
    runs-on: macos-latest
    needs: compile

    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Run Unit Tests
        run: npm run test

  integration_tests:
    name: Run Narrow Integration Tests
    runs-on: macos-latest
    needs: unit_tests

    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Run Narrow Integration Tests
        # TODO: replace with command for Narrow Integration Tests
        run: npm run test

  component_tests:
    name: Run Component Tests
    runs-on: macos-latest
    needs: integration_tests

    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Run Component Tests
        # TODO: replace with command for Component Tests
        run: npm run test

  verification_tests:
    name: Run Contract Provider Verification Tests
    runs-on: macos-latest
    needs: component_tests

    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Run Component Tests
        # TODO: replace with command for Contract Provider Verification Tests
        run: npm run test

  linter:
    name: Run Linter
    runs-on: macos-latest
    needs: verification_tests

    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Run ESLint
        run: npm run lint

  build:
    name: Build
    runs-on: macos-latest
    needs: linter
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Setup Environment
        uses: andrei-kim-3tsoftwarelabs/my-electron-app/.github/workflows/setup.yml@main
        with:
          node_version: "20"

      - name: Build
        run: npm run build

      - name: Test
        run: npm test --timeout=15000
