name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Use a single Node.js version for consistency

      - name: Install Dependencies
        run: |
          npm install
          npm install @eslint/eslintrc @typescript-eslint/parser @typescript-eslint/eslint-plugin  # Ensure TypeScript ESLint plugins are installed if needed

      - name: Run ESLint and Generate Report
        run: |
          npx eslint . -f json -o eslint-report.json || true  # Always return success
        continue-on-error: true

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.json
          if-no-files-found: ignore
          include-hidden-files: false
          
      - name: Run ESLint 
        run: | 
          npx eslint . || true  # Prevent ESLint errors from failing the step
        continue-on-error: true  # Ensure the job continues even if ESLint finds errors
          

  build:
    name: Build with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    needs: eslint  # Ensures that ESLint runs before build

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: |
        npm install
        npm install @eslint/eslintrc

    - name: Build
      run: |
        npx webpack