name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Use a single Node.js version for consistency

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true  # Ensure the job continues even if ESLint finds errors


  build:
    name: Build and Test on ${{ matrix.os.name }} with Node.js ${{ matrix.node-version }}
    strategy:
      matrix:
        os:
          - { name: 'linux', image: 'ubuntu-latest' }
          - { name: 'windows', image: 'windows-latest' }
          - { name: 'macos', image: 'macos-latest' }
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os.image }}
    needs: eslint  # Ensures that ESLint runs before build

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run make

      # Install necessary GUI dependencies on Linux
      - name: Install GUI Dependencies on Linux
        if: matrix.os.name == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libasound2 \
            libgbm-dev \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrender1 \
            libxcb1 \
            libxcb-render0 \
            libxcb-shape0 \
            libxcb-xfixes0 \
            libxcb1-dev

      - name: Run Tests
        run: npm test