name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: |
        npm install
        npm install @eslint/eslintrc

    - name: Run ESLint 
      run: | 
        npx eslint . || true  # Prevent ESLint errors from failing the step
      continue-on-error: true  # Ensure the job continues even if ESLint finds errors

    - name: Upload ESLint Report
      if: always()  # Ensure this step runs even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: eslint-report
        path: eslint-report.json  # Adjust if you output ESLint in JSON format

    - name: Build
      run: |
        npx webpack
